version: '2'
services:
  db-postgres11:
    network_mode: "host"
    image: 'postgres:11'
    volumes:
      - ./data/postgres11/data:/var/lib/postgresql/data
      - ./data/postgres11:/var/lib/postgresql
      - ./pg-init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
